version: "2"
services:
  datastore:
    image: busybox
    volumes:
      - bundle_install:/app/vendor/bundle
      - bundle:/app/.bundle
      - node_modules:/app/node_modules
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
    networks:
      - default
    volumes:
      - .:/app
    volumes_from:
      - datastore
    # command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]
volumes:
  mysql-data:
    driver: local
  bundle_install:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local